name: Firefox Extension CI
on:
  push:
    branches:
      - firefox
jobs:
  build:
    runs-on: ubuntu-latest
    name: Firefox Ext- Made in Malawi
    steps:
      - name: checkout code
        uses: actions/setup-node@v2
        with: 
          node-version: "14"
      - name: build step
        id: building
        uses: mitch1009/maction@v2
        with:
          who-to-greet: "Ochanza"
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          passcode: ${{secrets.PASSCODE}}
          recipients: '[{"email": "mitch.chanza@gmail.com", "name":"Mitch Chanza"}]'
          message: ${{ github.event.head_commit.message }}
          # upgrades to v2
      - name: final scripts
        run: |
          npm install
          echo $USER
          npm run sample

